### ISSUE TITLE
README not linking to Muffin project properly

### ISSUE THREAD

**Issue by IlyaSemenov** [klen/muffin-admin#2]
> Muffin-Admin -- an extension to Muffin_ that implements admin-interfaces

Muffin_ here is an invalid link that leads to a non-existent element (`<a href="#id15">Muffin_</a>`) rather than, expectedly, https://github.com/klen/muffin. Also, placing a period at the end of the sentence would be great :)

**Comment by klen** [comment]
Thank you for the PR. Going to fix it.
